export const products = [
    {
      id: 1,
      category: "Rostro",
      title: "Basi 1",
      price: 10,
      image: "images/Rostro/base1.jpg",
      description: "Base líquida para un acabado perfecto.",
      
    },
    {
      id: 2,
      category: "Rostro",
      title: "Blush 1",
      price: 25,
      image: "images/Rostro/blush1.jpg",
      description: "Base líquida para un acabado perfecto.",
    },
    {
        id: 3,
        category: "Rostro",
        title: "Corrector 1",
        price: 10,
        image: "images/Rostro/corrector1.jpg",
        description: "",
      },
      {
        id: 4,
        category: "Ojos",
        title: "Sombra 3",
        price: 25,
        image: "images/Ojos/sombras3.jpg",
        description: "",
      },
      {
        id: 5,
        category: "Ojos",
        title: "Sombra 4",
        price: 10,
        image: "images/Ojos/sombras4.jpg",
        description: "",
      },
      {
        id: 6,
        category: "Ojos",
        title: "Delineador 1",
        price: 25,
        image: "images/Ojos/delineador1.jpg",
        description: "",
      },
      {
        id: 7,
        category: "Ojos",
        title: "Delineador 2",
        price: 25,
        image: "images/Ojos/delineador2.jpg",
        description: "",
      },
      {
        id: 8,
        category: "Ojos",
        title: "Delineador 3",
        price: 25,
        image: "images/Ojos/delineador3.jpg",
        description: "",
      },
      {
        id: 9,
        category: "Ojos",
        title: "Mascara de pestaña 1",
        price: 25,
        image: "images/Ojos/mascara1.jpg",
        description: "",
      },
      {
        id: 10,
        category: "Ojos",
        title: "Mascara de pestaña 2",
        price: 25,
        image: "images/Ojos/mascara2.jpg",
        description: "",
      },
      {
        id: 11,
        category: "Ojos",
        title: "Mascara de pestaña 3",
        price: 25,
        image: "images/Ojos/mascara3.jpg",
        description: "",
      },
      {
        id: 12,
        category: "Labios",
        title: "Labial 1",
        price: 10,
        image: "images/Labios/labial1.jpg",
        description: "",
      },
      {
        id: 13,
        category: "Labios",
        title: "Labial 2",
        price: 10,
        image: "images/Labios/labial2.jpg",
        description: "",
      },
      {
        id: 14,
        category: "Labios",
        title: "Labial 3",
        price: 10,
        image: "images/Labios/labial4.jpg",
        description: "",
      },
      {
        id: 15,
        category: "Labios",
        title: "Gloss 1",
        price: 10,
        image: "images/Labios/gloss1.jpg",
        description: "",
      },
      {
        id: 16,
        category: "Labios",
        title: "Gloss2",
        price: 10,
        image: "images/Labios/gloss2.jpg",
        description: "",
      },
      {
        id: 17,
        category: "skincare",
        title: "Skincare 1",
        price: 10,
        image: "images/Skincare/skincare1.jpg",
        description: "",
      },
      {
        id: 18,
        category: "skincare",
        title: "Skincare 1",
        price: 10,
        image: "images/Skincare/skincare2.jpg",
        description: "",
      },
      {
        id: 19,
        category: "skincare",
        title: "Protecto solar 1",
        price: 10,
        image: "images/Skincare/protectorsolar1.jpg",
        description: "",
      },
      {
        id: 20,
        category: "skincare",
        title: "Protecto solar 2",
        price: 10,
        image: "images/Skincare/protectorsolar2.jpg",
        description: "",
      },
      {
        id: 21,
        category: "pestana",
        title: "Set of Bridel Eye Lashies",
        price: 10,
        image: "images/n5.png",
        description: "",
      },
    
  ];