export const products = [
    {
      id: 1,
      category: "rostro",
      title: "AOA Puff + Set Polvo Fijador",
      price: 3,
      image: "images/Rostro/polvo1.png",
      description: "Consigue una piel de ensueño con nuestra nueva fórmula + mejorada: polvos sedosos con un toque de cobertura transparente para fijar el maquillaje y prolongarlo. 2 acabados para una cobertura natural y sin brillos Brightening: corrige cualquier tono de piel, con un brillo que refleja la luz para un brillo natural sin brillo.",
      
    },
    {
      id: 2,
      category: "Rostro",
      title: "AOA Puff + Set Polvo Fijador",
      price: 3,
      image: "images/Rostro/polvo2.png",
      description: "Consigue una piel de ensueño con nuestra nueva fórmula + mejorada: polvos sedosos con un toque de cobertura transparente para fijar el maquillaje y prolongarlo. 2 acabados para una cobertura natural y sin brillos Translúcido: fija la claridad en todos los tonos de piel, perfecto para hornear + fijar los puntos más altos del rostro.",
    },
    {
        id: 3,
        category: "Rostro",
        title: "AOA Flawless Liquid Concealer - Tono: M1",
        price: 3,
        image: "images/Rostro/concealer-liquid-m1.png",
        description: "Aporta un acabado natural para tratar o borrar defectos, cicatrices, contornos + resaltados. Ligero + hidratante, es perfecto para las zonas más secas del rostro: debajo de los ojos, líneas de expresión, debajo de la nariz + más. Tono: M1",
      },
      {
        id: 4,
        category: "Rostro",
        title: "AOA Flawless Liquid Concealer - Tono: L3",
        price: 3,
        image: "images/Rostro/concealer-liquid-l3.png",
        description: "Aporta un acabado natural para tratar o borrar defectos, cicatrices, contornos + resaltados. Ligero + hidratante, es perfecto para las zonas más secas del rostro: debajo de los ojos, líneas de expresión, debajo de la nariz + más.",
      },
      {
        id: 5,
        category: "Rostro",
        title: "AOA Flawless Liquid Concealer - Tono: L2",
        price: 3,
        image: "images/Rostro/concealer-liquid-l2.png",
        description: "Aporta un acabado natural para tratar o borrar defectos, cicatrices, contornos + resaltados. Ligero + hidratante, es perfecto para las zonas más secas del rostro: debajo de los ojos, líneas de expresión, debajo de la nariz + más.",
      },
      {
        id: 6,
        category: "Rostro",
        title: "AOA Flawless Liquid Concealer - Tono: L1",
        price: 3,
        image: "images/Rostro/concealer-liquid-l1.png",
        description: "Aporta un acabado natural para tratar o borrar defectos, cicatrices, contornos + resaltados. Ligero + hidratante, es perfecto para las zonas más secas del rostro: debajo de los ojos, líneas de expresión, debajo de la nariz + más.",
      },
      {
        id: 7,
        category: "Ojos",
        title: "Duo de brochas F4 & E104 Kabuki",
        price: 4,
        image: "images/Rostro/pinceles-f4-e104.png",
        description: "- Fibras ultra afelpadas, densas y aterciopeladas diseñadas para ayudar a crear un acabado impecable, de alta definición y uniforme en cualquier iluminación. - Cerdas firmemente aseguradas para un desprendimiento mínimo - Las cerdas son sintéticas, lo que significa que todos nuestros pinceles son 100% libres de crueldad, gluten y veganos. - Mango resistente de tamaño completo, negro mate, los mangos de madera son duraderos y cómodos de sostener para un control total.",
      },
      {
        id: 8,
        category: "skincare",
        title: "Mascarilla facial cremosa de papaya",
        price: 2,
        image: "images/Skincare/mascarilla-facial-papaya.png",
        description: "Una fórmula cremosa lavable que ayuda a eliminar las impurezas, manteniendo la piel con un aspecto fresco e hidratado. Contiene extractos de papaya y lavanda para limpiar y purificar en profundidad.",
      },
      {
        id: 9,
        category: "skincare",
        title: "Mascarilla facial cremosa con vitamina E",
        price: 2,
        image: "images/Skincare/mascarilla-facial-ve.png",
        description: "Una fórmula cremosa lavable que ayuda a eliminar las impurezas, manteniendo la piel con un aspecto fresco e hidratado.",
      },
      {
        id: 10,
        category: "skincare",
        title: "Toallitas desmaquillantes AOA - Sin perfume",
        price: 2,
        image: "images/Skincare/toallitas-desmaquillante-sinperfume.png",
        description: "¡Las toallitas desmaquillantes AOA son esenciales como primer paso de limpieza! Estas toallitas AOA quitan todo el maquillaje del rostro con suavidad, sin dejar residuos jabonosos o grasos. Hechos de algodón ultra afelpado de alta calidad, se sienten suaves y tersos en la piel.",
      },
      {
        id: 11,
        category: "skincare",
        title: "Toallitas Desmaquillantes AOA - Agua de Rosas",
        price: 2,
        image: "images/Skincare/toallitas-desmaquillante-aguarosas.png",
        description: "¡Las toallitas desmaquillantes AOA son esenciales como primer paso de limpieza! Estas toallitas AOA quitan todo el maquillaje del rostro con suavidad, sin dejar residuos jabonosos o grasos. Hechos de algodón ultra afelpado de alta calidad, se sienten suaves y tersos en la piel.",
      },
      {
        id: 12,
        category: "skincare",
        title: "Alfombrilla de herramientas para el cabello resistente al calor AOA",
        price: 3,
        image: "images/Skincare/alfombrilla-calor.png",
        description: "- Hecho de silicona de alta calidad. - ¡Proteja los mostradores y las mesas de sus herramientas de peinado con calor! - Fácil de envolver alrededor de la herramienta y poner en su bolsa de viaje. - Soporta el calor hasta 460 grados F. - El diseño único evita que las herramientas se deslicen y se deslicen.",
      },
      {
        id: 13,
        category: "skincare",
        title: "Toalla de microfibra AOA",
        price: 2,
        image: "images/Skincare/toalla-microfibra.png",
        description: "¡Toalla de paño de microfibra que borra el maquillaje súper suave! ¡Incluso para pieles sensibles! Sostenible y respetuoso con el medio ambiente.",
      },
      {
        id: 14,
        category: "Rostro",
        title: "AOA Bamboo Almohadillas desmaquillantes reutilizables",
        price: 0.9,
        image: "images/Rostro/almohadillas-desmaquillantes.png",
        description: "♻️ RESPETUOSO CON EL MEDIO AMBIENTE Y CERO RESIDUOS ♻️ Reemplace sus rondas de algodón desechables con nuestras almohadillas desmaquillantes reutilizables. Diseñado para durar años de uso.",
      },
      {
        id: 15,
        category: "skincare",
        title: "Mascarilla facial de arcilla rosa",
        price: 3.5,
        image: "images/Skincare/mascarilla-rosa.png",
        description: "- Libre de parabenos y tiene ingredientes que equilibran el pH. - Se recomienda su uso 2-3 veces por semana para obtener los mejores resultados óptimos.",
      },
      {
        id: 16,
        category: "skincare",
        title: "AOA Skin Exfoliante Facial con Vitamina C",
        price: 2,
        image: "images/Skincare/skin-exfoliante-vc.png",
        description: "¡Hecho con vitamina C + aceite de semilla de jojoba para iluminar + exfoliar tu piel! - Exfoliante. - Energizante. - Antienvejecimiento.",
      },
      {
        id: 17,
        category: "skincare",
        title: "Organizador de maquillaje",
        price: 4,
        image: "images/Skincare/organizador-maquillaje.png",
        description: "- Organizador de maquillaje para tu baño o tocador. - ¡Ranuras para lápices labiales, bases de maquillaje y más! - Plástico esmerilado transparente.",
      },
      {
        id: 18,
        category: "skincare",
        title: "Organizador de brochas de maquillaje",
        price: 4,
        image: "images/Skincare/organizador-brochas.png",
        description: "- ¡El organizador perfecto para sujetar tus brochas de maquillaje! - También contiene lápices de maquillaje, herramientas y más - Plástico esmerilado transparente - Se puede usar en su escritorio para bolígrafos y lápices",
      },
      {
        id: 19,
        category: "skincare",
        title: "AOA Studio Juego de pinceles de alta definición de 10 piezas",
        price: 16,
        image: "images/Rostro/pinceles-10.png",
        description: "Presentamos AOA Studio Professional Kabuki 10 Brush Set, una colección de diez brochas de maquillaje vegano de tamaño completo estilo kabuki que te ayudan a contornear, esculpir, difuminar y resaltar un look impecable de rostro completo. Los cepillos cuentan con mangos de madera de color negro mate y rieles plateados que aseguran firmemente las cerdas aterciopeladas, densas y afelpadas para un desprendimiento mínimo.",
      },
      {
        id: 20,
        category: "Rostro",
        title: "Base de maquillaje AOA Satin Drops - Tono: L1",
        price: 3,
        image: "images/Rostro/base-l1.png",
        description: "¡Controla tu cobertura con AOA Satin Drops Foundation! Por qué nos encanta esto: - Ligero. - Acabado natural satinado que nunca se siente pesado. - Cobertura modulable y personalizable. - Larga duración.",
      },
      {
        id: 21,
        category: "Rostro",
        title: "Base de maquillaje AOA Satin Drops - Tono: L2",
        price: 3,
        image: "images/Rostro/base-l2.png",
        description: "¡Controla tu cobertura con AOA Satin Drops Foundation! Por qué nos encanta esto: - Ligero. - Acabado natural satinado que nunca se siente pesado. - Cobertura modulable y personalizable. - Larga duración.",
      },
      {
        id: 22,
        category: "Rostro",
        title: "Base de maquillaje AOA Satin Drops",
        price: 3,
        image: "images/Rostro/base-m1.png",
        description: "¡Controla tu cobertura con AOA Satin Drops Foundation! Por qué nos encanta esto: - Ligero. - Acabado natural satinado que nunca se siente pesado. - Cobertura modulable y personalizable. - Larga duración.",
      },
      {
        id: 23,
        category: "Labios",
        title: "AOA Magical Girl Tinte Labial - Tono: Hime",
        price: 3,
        image: "images/Labios/tinte-labial-hime.png",
        description: "¡El poder de tu belleza aumenta cuando realzas mágicamente tu mirada con un tinte de labios que dura horas!",
      },
      {
        id: 24,
        category: "Labios",
        title: "AOA Magical Girl Tinte Labial - Tono: Shion",
        price: 3,
        image: "images/Labios/tinte-labial-shion.png",
        description: "¡El poder de tu belleza aumenta cuando realzas mágicamente tu mirada con un tinte de labios que dura horas!",
      },
      {
        id: 25,
        category: "Labios",
        title: "AOA Magical Girl Tinte Labial - Tono: kuu",
        price: 3,
        image: "images/Labios/tinte-labial-kuu.png",
        description: "¡El poder de tu belleza aumenta cuando realzas mágicamente tu mirada con un tinte de labios que dura horas!",
      },
      {
        id: 26,
        category: "Rostro",
        title: "AOA Magical Girl Gloss Highlighter",
        price: 3,
        image: "images/Rostro/gloss-highlighter.png",
        description: "GLOSS HIGHLIGHTER Para labios, ojos + mejillas.",
      },
      {
        id: 27,
        category: "Ojos",
        title: "AOA Magical Girl Brow Lift - Cera para esculpir",
        price: 3,
        image: "images/Ojos/cera-cejas.png",
        description: "- MOLDEAR + ESCULPIR crear laminados, + otros looks virales de cejas. - FIJACIÓN FUERTE dura todo el día o la noche.",
      },
      {
        id: 28,
        category: "Labios",
        title: "AOA I Heart Dew Lip Oil - Tono: Glow",
        price: 3,
        image: "images/Labios/lip-oil-glow.png",
        description: "Suaviza, + protege tus labios de la deshidratación + agrietamiento con una cucharada de brillo nutritivo - No pegajoso. - Nutritivo. - Protector. - Hidratante.",
      },
      {
        id: 29,
        category: "Labios",
        title: "AOA I Heart Dew Lip Oil - Tono: Glass",
        price: 3,
        image: "images/Labios/lip-oil-glass.png",
        description: "Suaviza, + protege tus labios de la deshidratación + agrietamiento con una cucharada de brillo nutritivo - No pegajoso. - Nutritivo. - Protector. - Hidratante.",
      },
      {
        id: 30,
        category: "Rostro",
        title: "AOA Locked Creamy Concealer - Tonos: LW1, LC2, MW1, MN1",
        price: 3,
        image: "images/Rostro/concealer-creamy.png",
        description: "Corrector cremoso pero transpirable en 12 tonos de larga duración con varita doe foot fácil que se aplica de manera uniforme + rápida.",
      },
      {
        id: 31,
        category: "Rostro",
        title: "AOA Pore Filling Primer",
        price: 3,
        image: "images/Rostro/primer-pore-aoa.png",
        description: "¡AOA Pore Filling Primer crea una piel suave y uniforme para el maquillaje! Esta prebase texturizada sedosa como una nube crea la base para cualquier look de maquillaje mientras ayuda a minimizar + difuminar la apariencia de los poros + piel texturizada, con un acabado mate. Apto para todo tipo de pieles.",
      },
      {
        id: 32,
        category: "skincare",
        title: "AOA Cepillo Desenredante para el Cabello",
        price: 3,
        image: "images/Skincare/cepillo-desenredante.png",
        description: "Color: Negro, rosado. - Cepillo desenredante para cabello húmedo o seco. - Ayuda a prevenir la rotura y cepilla suavemente el cabello.",
      },
      {
        id: 33,
        category: "Rostro",
        title: "AOA Plush Blush - Gel Liquid Blush",
        price: 3,
        image: "images/Rostro/blush-gel-liquid.png",
        description: "- Colorete líquido ligero tipo gel. - Da el brillo más natural desde el interior. - Frota suavemente el rubor en las mejillas y difumina con los dedos.",
      },
      {
        id: 34,
        category: "Rostro",
        title: "AOA Cherry Blossom Powder Blushes - Tonos: Shūrei, Kioko",
        price: 3,
        image: "images/Rostro/blush-cherryblossom.png",
        description: "- Coloretes suaves. - Disponible en magníficos tonos inspirados en la flor de cerezo.",
      },
      {
        id: 35,
        category: "Ojos",
        title: "Paw Paw Waterproof Eye Makeup Sealer + Mixing Fluid",
        price: 3,
        image: "images/Ojos/waterproof-eye-sealer-pawpaw.png",
        description: "- Un convertidor de líquidos que transforma las fórmulas en polvo y los lápices en un maquillaje a prueba de manchas que dura todo el día - ¡Mézclalo con tu maquillaje en polvo para sellarlo y hacerlo resistente al agua! - ¡Se puede usar con sombras de ojos, brillos, delineadores y más!",
      },
      {
        id: 36,
        category: "Ojos",
        title: "AOA Máscara de pestañas impactante",
        price: 3,
        image: "images/Ojos/mascara-aoa.png",
        description: "Efecto: Length, Curl, Volume. Estas máscaras AOA A+ dan longitud y volumen a tus pestañas. Es una fórmula duradera que nunca se ejecutará en ti. Esta máscara de pestañas a prueba de manchas es buena para los ojos sensibles y no deja grumos.",
      },
      {
        id: 37,
        category: "Ojos",
        title: "AOA Pencil Gel Eyeliner",
        price: 2,
        image: "images/Ojos/pencil-gel-eyeliner.png",
        description: "¡Un lápiz delineador de ojos cremoso y duradero de AOA Studio! - Negro para el delineador de ojos más atrevido - Marrón oscuro para un color profundo que es hipnotizante, pero no demasiado oscuro.",
      },
      {
        id: 38,
        category: "skincare",
        title: "A+ Champú Cepillo Masajeador de cuero cabelludo - Engrase del cabello",
        price: 4,
        image: "images/Skincare/cepillo-cabello.png",
        description: "Colores: Azul, rosado, beige, gris. ¡Ideal para engrasar el cabello y masajear sueros en el cuero cabelludo para estimular la circulación sanguínea y tener un cabello sano! - 44 cerdas de silicona suave. - Exfoliar el cuero cabelludo. - Ayuda con la caspa. - Promover el crecimiento saludable del cabello..",
      },
      {
        id: 39,
        category: "skincare",
        title: "AOA Espejo de mano de estudio",
        price: 2,
        image: "images/Skincare/espejo-aoa.png",
        description: "¡Espejo de mano AOA Studio! ¡Tamaño perfecto para tu bolsa de maquillaje y de viaje! ¡Forma cuadrada!",
      },
      {
        id: 40,
        category: "Ojos",
        title: "AOA Studio Wisp Color Mascara",
        price: 3,
        image: "images/Ojos/mascara-aoa.png",
        description: "The AOA Wisp Color Mascara es una hermosa máscara de pestañas que da volumen, levanta y alarga las pestañas al instante mientras agrega un efecto de color caprichoso. ¡Trabaja a través de las pestañas desde la raíz hasta las puntas y construye hasta la intensidad deseada! Azul oscuro: Un azul real profundo que ilumina los ojos y agrega un hermoso toque de color Verde oscuro: sensual e impresionante, ¡ideal para cualquier color de ojos!",
      },
      {
        id: 41,
        category: "Rostro",
        title: "Paw Paw: Prowear Foundation - Tonos claros",
        price: 3,
        image: "images/Rostro/base-pawpaw.png",
        description: "Tonos: Porcelain, Nude, Natural Beige, Soft Tan, Honey Beige. ¡Esta base de maquillaje de cobertura media a completa con un hermoso acabado semimate es la base de tus sueños!",
      },
      {
        id: 42,
        category: "Rostro",
        title: "Spray fijador A+",
        price: 3,
        image: "images/Rostro/spary-fijador.png",
        description: "Una micro bruma refrescante y ligera que fija el maquillaje para un acabado duradero. La piel se mantiene cómoda con una mezcla de ingredientes naturalmente refrescantes para un impulso instantáneo. Se siente totalmente indetectable en la piel, sin tirantez ni residuos pegajosos. - Bruma en el rostro después de la aplicación del maquillaje. - Refrescante aroma a agua de rosas. - El tamaño es de 75 ml/2.5 oz.",
      },
      {
        id: 43,
        category: "Rostro",
        title: "Papel secante de estudio AOA",
        price: 2,
        image: "images/Skincare/papel-secante.png",
        description: "Controla y borra el brillo a lo largo del día con los papeles Blotting de AOA Studio ! ¡Estos papeles secantes ayudan a mantener el maquillaje recién aplicado durante todo el día! - Sin perfume: perfecto para todo tipo de pieles, incluso para pieles sensibles - Fácil de transportar - 50 hojas en cada paquete",
      },
      {
        id: 44,
        category: "Rostro",
        title: "Dúo de pinceles Kabuki F1 y E101",
        price: 4,
        image: "images/Rostro/pinceles-f1-e101.png",
        description: "Este set DUO incluye un pincel grande F1 Flat Top y un E101 Flat Top Precision Brush - Fibras ultra afelpadas, densas y aterciopeladas diseñadas para ayudar a crear un acabado impecable, de alta definición y uniforme en cualquier iluminación. - Cerdas firmemente aseguradas para un desprendimiento mínimo. - Las cerdas son sintéticas. - Mango resistente de tamaño completo, negro mate, los mangos de madera son duraderos y cómodos de sostener.",
      },
      {
        id: 45,
        category: "Rostro",
        title: "Dúo de pinceles Kabuki F2 y E102",
        price: 4,
        image: "images/Rostro/pinceles-f2-e102.png",
        description: "Este set DUO incluye un pincel grande F1 Flat Top y un E101 Flat Top Precision Brush - Fibras ultra afelpadas, densas y aterciopeladas diseñadas para ayudar a crear un acabado impecable, de alta definición y uniforme en cualquier iluminación. - Cerdas firmemente aseguradas para un desprendimiento mínimo. - Las cerdas son sintéticas. - Mango resistente de tamaño completo, negro mate, los mangos de madera son duraderos y cómodos de sostener.",
      },
      {
        id: 46,
        category: "Rostro",
        title: "Bolsa de maquillaje AOA",
        price: 4,
        image: "images/Rostro/bolsa-de-maquillaje.png",
        description: "Colores: Negro, Rosado. ¡Mantén tu reserva de maquillaje claramente organizada + lista para llevar contigo a cualquier parte! - Ventana esmerilada transparente para artículos de identificación rápida. - Fácil de viajar. - Resistente al agua. - Ahorro de espacio.",
      },
      {
        id: 47,
        category: "Skincare",
        title: "Cintillo para maquillaje",
        price: 5,
        image: "images/Skincare/cintillo.png",
        description: "Colores: Rosado, Negro",
      },
      {
        id: 48,
        category: "Rostro",
        title: "Borlas de maquillaje",
        price: 1,
        image: "images/Rostro/borlas.png",
        description: "",
      },
      {
        id: 49,
        category: "Rostro",
        title: "Rizadora sin calor",
        price: 5,
        image: "images/Skincare/rizador.png",
        description: "",
      },
      {
        id: 49,
        category: "Rostro",
        title: "Esponjas",
        price: 1,
        image: "images/Rostro/esponja1.png",
        description: "",
      },
      {
        id: 50,
        category: "Skincare",
        title: "Pinzas para el pelo",
        price: 0.5,
        image: "images/Skincare/pinzas-pelo.png",
        description: "",
      },
      {
        id: 51,
        category: "Rostro",
        title: "Mini esponjas",
        price: 0.5,
        image: "images/Rostro/mini-esponjas.png",
        description: "",
      },
  ];